services:
  - type: web
    name: personal-energy-waste-api
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false