(function(){
  const gate=document.getElementById('authGate'), app=document.querySelector('.app-shell'), login=document.getElementById('loginButton'), logout=document.getElementById('logoutButton'), error=document.getElementById('authError');
  if(!window.firebase||!window.ENERGY_CONFIG||!window.ENERGY_CONFIG.firebase||window.ENERGY_CONFIG.firebase.apiKey==='your-web-api-key'){error.textContent='Set the Firebase web configuration in web/config.js before signing in.';return;}
  const showError=e=>{error.textContent=e.message||'Sign-in failed. Please try again.'};
  const apiCall=(path,options)=>window.api(path,options);
  async function loadUser(user){window.state.token=await user.getIdToken();const [appliances,settings]=await Promise.all([apiCall('/api/appliances'),apiCall('/api/settings')]);window.state.appliances=appliances.map(window.fromApi);window.state.tariff=Number(settings.electricityRate)||8;document.getElementById('tariff').value=window.state.tariff;window.state.ready=true;gate.classList.add('hidden');app.classList.add('ready');window.render()}
  login.addEventListener('click',async()=>{try{await window.state.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())}catch(e){showError(e)}});
  logout.addEventListener('click',()=>window.state.auth.signOut());
  window.state.auth.onAuthStateChanged(async user=>{if(!user){window.state.ready=false;window.state.token=null;window.state.appliances=[];gate.classList.remove('hidden');app.classList.remove('ready');return}try{await loadUser(user)}catch(e){showError(e)}});
  document.getElementById('applianceForm').addEventListener('submit',async event=>{event.preventDefault();event.stopImmediatePropagation();const a={id:document.getElementById('editId').value||'',name:document.getElementById('name').value.trim(),power:Number(document.getElementById('power').value),units:Number(document.getElementById('units').value),hours:Number(document.getElementById('hours').value),days:Number(document.getElementById('days').value),necessary:Number(document.getElementById('necessary').value)};if(!a.name||a.power<=0||a.units<=0||a.hours<0||a.hours>24||a.days<1||a.days>31||a.necessary<0||a.necessary>a.hours){document.getElementById('formError').textContent='Please check every value. Necessary hours cannot exceed actual hours.';return}try{const saved=await apiCall(a.id?`/api/appliances/${a.id}`:'/api/appliances',{method:a.id?'PUT':'POST',body:JSON.stringify(window.toApi(a))});const index=window.state.appliances.findIndex(x=>x.id===a.id);if(index>=0)window.state.appliances[index]=window.fromApi(saved);else window.state.appliances.push(window.fromApi(saved));window.closeModal();window.render()}catch(e){document.getElementById('formError').textContent=e.message}} ,true);
  document.addEventListener('click',async event=>{const del=event.target.closest('[data-delete]');if(!del)return;event.preventDefault();event.stopImmediatePropagation();if(!confirm('Remove this appliance?'))return;try{await apiCall(`/api/appliances/${del.dataset.delete}`,{method:'DELETE'});window.state.appliances=window.state.appliances.filter(a=>a.id!==del.dataset.delete);window.render()}catch(e){showError(e)}},true);
  document.getElementById('sampleButton').addEventListener('click',async event=>{event.preventDefault();event.stopImmediatePropagation();const samples=[['Ceiling Fan',75,2,8,30,5],['Air Conditioner',1500,1,4,30,3],['Television',120,1,5,30,4],['Refrigerator',180,1,12,30,12]];try{for(const [name,power,units,hours,days,necessary] of samples){const saved=await apiCall('/api/appliances',{method:'POST',body:JSON.stringify(window.toApi({name,power,units,hours,days,necessary}))});window.state.appliances.push(window.fromApi(saved))}window.render()}catch(e){showError(e)}},true);
  document.getElementById('tariff').addEventListener('change',async event=>{event.stopImmediatePropagation();const value=Number(event.target.value);if(value>0){try{await apiCall('/api/settings',{method:'PUT',body:JSON.stringify({electricityRate:value,currency:'Rs.'})});window.state.tariff=value;window.render()}catch(e){showError(e)} }},true);
  document.getElementById('runSimulation').addEventListener('click',async()=>{const appliance=window.state.appliances.find(x=>String(x.id)===document.getElementById('simAppliance').value);if(!appliance)return;const simulated=Number(document.getElementById('simHours').value),current=window.totals().monthly,simulatedEnergy=current-window.calculator.monthly(appliance)+appliance.power*appliance.units*simulated*appliance.days/1000;const saved=Math.max(0,current-simulatedEnergy);await apiCall('/api/simulations',{method:'POST',body:JSON.stringify({applianceId:appliance.id,simulationType:'hours',originalUsage:appliance.hours,simulatedUsage:simulated,originalEnergy:current,simulatedEnergy,energySaved:saved,costDifference:saved*window.state.tariff})}).catch(showError)},false);
})();